CREATE TABLE IF NOT EXISTS `pre_health_snapshot` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `snapshot_time` datetime NOT NULL,
  `period_start` datetime NOT NULL,
  `period_end` datetime NOT NULL,
  `scope_type` varchar(20) NOT NULL,
  `scope_id` varchar(32) NOT NULL DEFAULT '0',
  `metrics_json` longtext NOT NULL,
  `metrics_version` varchar(20) NOT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_snapshot_scope` (`snapshot_time`,`scope_type`,`scope_id`,`metrics_version`),
  KEY `idx_scope_time` (`scope_type`,`scope_id`,`snapshot_time`),
  KEY `idx_period` (`period_start`,`period_end`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `pre_health_report` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `report_date` date NOT NULL,
  `report_type` varchar(20) NOT NULL DEFAULT 'daily',
  `period_start` datetime NOT NULL,
  `period_end` datetime NOT NULL,
  `health_level` varchar(20) NOT NULL,
  `metrics_json` longtext NOT NULL,
  `rules_json` longtext NOT NULL,
  `ai_status` tinyint(1) NOT NULL DEFAULT '0',
  `ai_provider` varchar(40) DEFAULT NULL,
  `ai_model` varchar(100) DEFAULT NULL,
  `ai_duration_ms` int(11) DEFAULT NULL,
  `ai_json` longtext DEFAULT NULL,
  `ai_error` varchar(500) DEFAULT NULL,
  `ai_attempted_at` datetime DEFAULT NULL,
  `ai_request_sha256` char(64) DEFAULT NULL,
  `ai_response_sha256` char(64) DEFAULT NULL,
  `ai_started_at` datetime DEFAULT NULL,
  `ai_completed_at` datetime DEFAULT NULL,
  `ai_retry_until` datetime DEFAULT NULL,
  `ai_next_retry_at` datetime DEFAULT NULL,
  `ai_calls` int(11) NOT NULL DEFAULT '0',
  `ai_source_rows` int(11) NOT NULL DEFAULT '0',
  `ai_sample_rows` int(11) NOT NULL DEFAULT '0',
  `ai_drilldown_rows` int(11) NOT NULL DEFAULT '0',
  `ai_payload_mode` varchar(16) NOT NULL DEFAULT 'compact',
  `ai_request_bytes` bigint(20) unsigned NOT NULL DEFAULT '0',
  `ai_response_bytes` bigint(20) unsigned NOT NULL DEFAULT '0',
  `ai_input_tokens` bigint(20) unsigned NOT NULL DEFAULT '0',
  `ai_output_tokens` bigint(20) unsigned NOT NULL DEFAULT '0',
  `ai_token_source` varchar(16) DEFAULT NULL,
  `ai_pipeline_version` varchar(32) DEFAULT NULL,
  `telegram_status` tinyint(1) NOT NULL DEFAULT '0',
  `telegram_queue_id` bigint(20) unsigned DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `sent_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_report_date_type` (`report_date`,`report_type`),
  KEY `idx_level_date` (`health_level`,`report_date`),
  KEY `idx_telegram_status` (`telegram_status`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `pre_health_ai_task` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `report_id` bigint(20) unsigned NOT NULL,
  `stage` varchar(40) NOT NULL,
  `scope_type` varchar(20) NOT NULL,
  `scope_id` varchar(32) NOT NULL DEFAULT '0',
  `chunk_no` int(11) NOT NULL DEFAULT '0',
  `status` tinyint(1) NOT NULL DEFAULT '0',
  `source_rows` int(11) NOT NULL DEFAULT '0',
  `payload_bytes` int(11) unsigned NOT NULL DEFAULT '0',
  `request_payload_sha256` char(64) NOT NULL,
  `request_sha256` char(64) DEFAULT NULL,
  `response_sha256` char(64) DEFAULT NULL,
  `request_bytes` int(11) unsigned NOT NULL DEFAULT '0',
  `response_bytes` int(11) unsigned NOT NULL DEFAULT '0',
  `input_tokens` int(11) unsigned NOT NULL DEFAULT '0',
  `output_tokens` int(11) unsigned NOT NULL DEFAULT '0',
  `token_source` varchar(16) DEFAULT NULL,
  `duration_ms` int(11) DEFAULT NULL,
  `result_json` longtext DEFAULT NULL,
  `error_message` varchar(500) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `completed_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_report_stage` (`report_id`,`stage`,`scope_id`,`chunk_no`),
  KEY `idx_daily_budget` (`created_at`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
