<?php
if(PHP_SAPI === 'cli') exit(1);
$view = isset($_GET['view']) && $_GET['view'] === 'detail' ? 'detail' : 'list';
function fixture_h($value){ return htmlspecialchars((string)$value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'); }
$attackTitle = '<img src=x onerror=window.__xss=1>';
$attackContent = '<script>window.__xss=1</script> 用户反馈内容很长，用于验证移动端能够正常换行而不会撑破页面。';
?><!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>商户投诉只读中心夹具</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#f4f6f8;color:#333;font:14px/1.5 Arial,sans-serif}.shell{max-width:1120px;margin:auto;padding:20px}.title{font-size:24px;margin:0 0 16px}.notice{padding:12px;border:1px solid #bce8f1;background:#d9edf7;color:#31708f;margin-bottom:15px}.complaint-summary{display:grid;grid-template-columns:repeat(4,minmax(120px,1fr));gap:10px;margin-bottom:15px}.complaint-summary-item,.panel{border:1px solid #dee5e7;background:#fff}.complaint-summary-item{padding:12px 14px}.complaint-summary-label{color:#777;font-size:12px}.complaint-summary-value{margin-top:3px;font-size:22px}.panel-title{margin:0;padding:12px 14px;border-bottom:1px solid #dee5e7;font-size:16px}.toolbar{display:flex;gap:8px;flex-wrap:wrap;padding:12px}.toolbar input,.toolbar select,.button{min-height:36px;border:1px solid #ccd2d8;background:#fff;padding:7px 10px}.button{display:inline-block;color:#fff;background:#168de2;text-decoration:none}.table-wrap{overflow-x:auto}table{width:100%;border-collapse:collapse;table-layout:fixed}th,td{padding:10px;border:1px solid #e4e8ec;text-align:left;vertical-align:top;overflow-wrap:anywhere}.complaint-detail-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0 28px;padding:14px}.complaint-field{padding:9px 0;border-bottom:1px solid #edf1f2}.complaint-field-label{margin-bottom:4px;color:#777;font-size:12px}.complaint-field-value{min-height:20px;overflow-wrap:anywhere;white-space:pre-wrap}.complaint-content{margin:0 14px 14px;padding:12px;border:1px solid #dee5e7;background:#f9fafb;line-height:1.7;overflow-wrap:anywhere;white-space:pre-wrap}.actions{padding:0 14px 14px}@media(max-width:767px){.shell{padding:12px}.complaint-summary{grid-template-columns:repeat(2,minmax(0,1fr))}.complaint-summary-value{font-size:18px}.toolbar>*{width:100%}.complaint-detail-grid{grid-template-columns:1fr}table{min-width:760px}.title{font-size:20px}}
</style></head><body><main class="shell">
<?php if($view === 'list'){?>
<h1 class="title">交易投诉</h1><div class="complaint-summary"><div class="complaint-summary-item"><div class="complaint-summary-label">全部投诉</div><div class="complaint-summary-value">4</div></div><div class="complaint-summary-item"><div class="complaint-summary-label">待处理</div><div class="complaint-summary-value">1</div></div><div class="complaint-summary-item"><div class="complaint-summary-label">处理中</div><div class="complaint-summary-value">2</div></div><div class="complaint-summary-item"><div class="complaint-summary-label">处理完成</div><div class="complaint-summary-value">1</div></div></div>
<div class="notice">此页面仅展示本商户投诉和关联订单信息。退款、回复及投诉状态处理请联系平台管理员。</div>
<section class="panel"><h2 class="panel-title">投诉订单记录</h2><div class="toolbar"><select aria-label="搜索字段"><option>系统订单号</option></select><input aria-label="搜索内容" placeholder="搜索内容"><input aria-label="开始日期" placeholder="开始日期"><input aria-label="结束日期" placeholder="结束日期"><button class="button">搜索</button></div><div class="table-wrap"><table><thead><tr><th>订单号</th><th>商品/金额</th><th>支付方式</th><th>问题类型/投诉原因</th><th>状态</th><th>操作</th></tr></thead><tbody><tr><td>202607210001<br>M-17</td><td><?php echo fixture_h('<script>alert(1)</script>');?> / ￥31.00</td><td>支付宝</td><td>商品问题<br><?php echo fixture_h($attackTitle);?></td><td>待处理</td><td><a class="button" href="?view=detail">查看详情</a></td></tr></tbody></table></div></section>
<?php }else{?>
<h1 class="title">投诉详情</h1><div class="notice">此页面仅展示平台已保存的信息。投诉处理、退款及回复由平台管理员完成。</div><section class="panel"><h2 class="panel-title">投诉记录 #17</h2><div class="complaint-detail-grid"><div class="complaint-field"><div class="complaint-field-label">处理状态</div><div class="complaint-field-value">处理完成</div></div><div class="complaint-field"><div class="complaint-field-label">第三方投诉单号</div><div class="complaint-field-value">THIRD-COMPLAINT-17</div></div><div class="complaint-field"><div class="complaint-field-label">投诉原因</div><div class="complaint-field-value"><?php echo fixture_h($attackTitle);?></div></div><div class="complaint-field"><div class="complaint-field-label">联系电话</div><div class="complaint-field-value">138****8000</div></div></div><h3 class="panel-title">投诉内容</h3><div class="complaint-content"><?php echo fixture_h($attackContent);?></div><div class="actions"><a class="button" href="?view=list">返回投诉列表</a></div></section>
<?php }?>
</main></body></html>
